id: P004424
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:20:22.704528
source_metadata:
  id: bdr:W3CN4705
  title: འདུལ་ཊཱིཀ་ཉི་མའི་འོད་ཟེར།
  author: ''
  volumes:
    da12b890216443889acf45152eca7758:
      image_group_id: I3CN4707
      title: ''
      volume_number: 1
      total_pages: 776
      base_file: v001.txt
    22c4417edc354fe8bfe8a01d2fc83bb3:
      image_group_id: I3CN4708
      title: ''
      volume_number: 2
      total_pages: 440
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
