id: I26972DAA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T21:48:27+00:00'
last_modified: '2022-06-08T00:55:19.553509+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4705
  title: འདུལ་ཊཱིཀ་ཉི་མའི་འོད་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CB07:
      image_group_id: I3CN4707
      title: ''
      total_pages: 776
      order: 1
      base_file: CB07.txt
    A4EE:
      image_group_id: I3CN4708
      title: ''
      total_pages: 440
      order: 2
      base_file: A4EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
